module.exports = {
  rules: {
    'arrow-body-style': 0,
    'arrow-parens': 0,
    'arrow-spacing': [2, { 'before': true, 'after': true }],
    'constructor-super': 2,
    'generator-star-spacing': 0,
    'no-class-assign': 2,
    'no-confusing-arrow': 0,
    'no-const-assign': 2,
    'no-dupe-class-members': 2,
    'no-new-symbol': 2,
    'no-this-before-super': 2,
    'no-useless-constructor': 0,
    'no-var': 0,
    'object-shorthand': [2, 'always'],
    'prefer-arrow-callback': 0,
    'prefer-const': 1,
    'prefer-reflect': 2,
    'prefer-rest-params': 2,
    'prefer-spread': 2,
    'prefer-template': 2,
    'require-yield': 2,
    'template-curly-spacing': 0,
    'yield-star-spacing': 0,
  },
};
