module.exports = {
  rules: {
    'array-bracket-spacing': 0,
    'block-spacing': [2, 'always'],
    'brace-style': 2,
    'camelcase': 2,
    'comma-spacing': [2, { 'before': false, 'after': true }],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': 0,
    'eol-last': 2,
    'func-names': 1,
    'func-style': 0,
    'id-blacklist': 0,
    'id-length': 0,
    'id-match': 0,
    'indent': [
      2,
      2,
      { 
        'VariableDeclarator': { 'var': 2, 'let': 2, 'const': 3 },
        'SwitchCase': 1,
      },
    ],
    'jsx-quotes': 0,
    'key-spacing': [2, { 'beforeColon': false, 'afterColon': true }],
    'keyword-spacing': 2,
    'linebreak-style': [2, 'unix'],
    'lines-around-comment': 0,
    'max-depth': 0,
    'max-len': [
      2,
      {
        'code': 100,
        'tabWidth': 4,
        'ignoreUrls': true,
      },
    ],
    'max-nested-callbacks': 0,
    'max-params': 0,
    'max-statements': 0,
    'new-cap': 2,
    'new-parens': 0,
    'newline-after-var': 0,
    'newline-per-chained-call': 0,
    'no-array-constructor': 2,
    'no-bitwise': 0,
    'no-continue': 0,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multiple-empty-lines': 0,
    'no-negated-condition': 0,
    'no-nested-ternary': 2,
    'no-new-object': 0,
    'no-plusplus': 0,
    'no-restricted-syntax': [2, 'WithStatement'],
    'no-spaced-func': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': [2, { 'defaultAssignment': true }],
    'no-whitespace-before-property': 2,
    'object-curly-spacing': [2, 'always'],
    'one-var': 0,
    'one-var-declaration-per-line': 0,
    'operator-assignment': 0,
    'operator-linebreak': 0,
    'padded-blocks': 0,
    'quote-props': [2, 'consistent-as-needed', { 'keywords': true }],
    'quotes': [2, 'single', 'avoid-escape'],
    'require-jsdoc': 0,
    'semi': [2, 'always'],
    'semi-spacing': [2, { 'before': false, 'after': true }],
    'sort-imports': 0,
    'sort-vars': 0,
    'space-before-blocks': 2,
    'space-before-function-paren': [
      2,
      { 'anonymous': 'always', 'named': 'never' },
    ],
    'space-in-parens': 0,
    'space-infix-ops': 2,
    'space-unary-ops': 0,
    'spaced-comment': 0,
    'wrap-regex': 0,
  },
};
